---
- name: CityFan repository added (CentOS/RHEL 6)
  yum_repository:
    name: city-fan
    description: City Fan Repo
    baseurl: http://nervion.us.es/city-fan/yum-repo/rhel$releasever/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-city-fan.org
    gpgcheck: no
    enabled: no

- name: libcurl installed
  yum:
    name: "{{ item }}"
    enablerepo: city-fan,epel
    state: latest
  with_items:
    - libcurl
    - libcurl-devel
