---
- name: httpd installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - httpd
      - httpd-devel

- block:
  - name: mod_proxy_fcgi installed
    package:
      name: mod_proxy_fcgi
  - name: httpd config (CentOS/RHEL 6)
    include: conf-centos6.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 6

- name: httpd config (CentOS/RHEL 7)
  include: conf-centos7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7

- name: httpd started and enabled
  service:
    name: httpd
    state: restarted
    enabled: yes
