---
- name: "VAW (Vagrant Ansible WordPress) v0.2.1"
  hosts: localhost
  user: vagrant
  sudo: yes

  roles:
    - { role: before-command, tags: [before-command] }
    - { role: common, tags: [common] }
    - { role: git, tags: [git] }
    - { role: mysql, tags: [mysql], when: "database == 'mysql'" }
    - { role: mariadb, tags: [mariadb], when: "database == 'mariadb'" }
    - { role: percona, tags: [percona], when: "database == 'percona'" }
    - { role: openssl, tags: [openssl], when: "ssl_admin == true or (server == 'apache' and server_tuning == true)" }
    - { role: apache, tags: [apache], when: "server == 'apache'" }
    - { role: nginx, tags: [nginx], when: "server == 'nginx'" }
    - { role: phpenv, tags: [phpenv] }
    - { role: hhvm, tags: [hhvm], when: "server == 'nginx' and fastcgi == 'hhvm'" }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: wordpress, tags: [wordpress] }
    - { role: rbenv, tags: [rbenv], when: "develop_tools == true or deploy_tools == true" }
    - { role: wordpress-develop, tags: [wordpress-develop], when: "develop_tools == true" }
    - { role: wordpress-deploy, tags: [wordpress-deploy], when: "deploy_tools == true" }
    - { role: after-command, tags: [after-command] }
