---
- name: stat import_xml_data
  stat:
    path: "{{ import_xml_data }}"
  register: is_xml_import

- block:
  - name: plugin install wordpress-importer
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} plugin install wordpress-importer --activate

  - name: import xml data
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} import {{ import_xml_data }} --authors=create

  - name: plugin deactivate wordpress-importer
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} plugin deactivate wordpress-importer
  when: is_xml_import.stat.exists and is_xml_import.stat.isdir == false and import_db_data == '' and theme_unit_test == false


- name: stat import_db_data
  stat:
    path: "{{ import_db_data }}"
  register: is_db_import

- block:
  - name: db data import
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} db import {{ import_db_data }}

  - name: add user admin
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} user create {{ admin_user }} {{ admin_email }} --user_pass={{ admin_password }} --role=administrator
    when: import_admin == true
  when: is_db_import.stat.exists and is_db_import.stat.isdir == false and import_xml_data == '' and theme_unit_test == false

- include: backwpup.yml

- name: get wordpress unit-test data
  get_url:
    url: "{{ unit_test_url }}"
    dest: "/tmp/theme-unit-test-data.xml"
    force: yes
    validate_certs: no
  when: theme_unit_test == true and lang != 'ja' and import_xml_data == '' and import_db_data == ''

- name: get wordpress unit-test-ja data
  get_url:
    url: "{{ unit_test_ja_url }}"
    dest: "/tmp/theme-unit-test-data.xml"
    force: yes
    validate_certs: no
  when: theme_unit_test == true and lang == 'ja' and import_xml_data == '' and import_db_data == ''

- name: stat theme-unit-test-data.xml
  stat:
    path: "/tmp/theme-unit-test-data.xml"
  register: is_unit_test

- block:
  - name: plugin install wordpress-importer
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} plugin install wordpress-importer --activate

  - name: import theme-unit-test-data.xml
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} import --authors=create /tmp/theme-unit-test-data.xml --authors=create

  - name: plugin deactivate wordpress-importer
    command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} plugin deactivate wordpress-importer

  - name: delete theme-unit-test-data.xml
    file:
      path: "/tmp/theme-unit-test-data.xml"
      state: absent
  when: is_unit_test.stat.exists and import_xml_data == '' and import_db_data == ''


- name: stat wp-content
  stat:
    path: /vagrant/wp-content
  register: is_wp_content

- name: rsync wp-content dir
  synchronize:
    src: /vagrant/wp-content
    dest: "{{ WP_PATH }}"
  when: is_wp_content.stat.exists and is_wp_content.stat.isdir == true


- name: stat uploads
  stat:
    path: /vagrant/uploads
  register: is_uploads

- name: rsync uploads dir
  synchronize:
    src: /vagrant/uploads
    dest: "{{ WP_PATH }}/wp-content"
  when: is_uploads.stat.exists and is_uploads.stat.isdir == true


- name: replace old url
  command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} search-replace {{ replace_old_url }} {{ WP_URL }} --precise --recurse-objects
  when: replace_old_url != ''

- name: regenerate thumbnails
  command: sudo -u vagrant -i -- {{ WP_CLI }} --path={{ WP_PATH }} media regenerate --yes
  when: regenerate_thumbnails == true
