---
- block:
  - name: hop5.repo repository added (CentOS/RHEL 6)
    yum_repository:
      name: hop5
      description: www.hop5.in Centos Repository
      baseurl: http://www.hop5.in/yum/el6/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-HOP5
      enabled: no
      gpgcheck: no

  - name: hhvm installed (CentOS/RHEL 6)
    package: name=hhvm enablerepo=hop5

  - name: init.d added
    template: src=init.d.hhvm.j2 dest=/etc/init.d/hhvm

  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6

- block:
  - name: gleez repository installed (CentOS/RHEL 7)
    yum: name=http://yum.gleez.com/6/x86_64/gleez-repo-6-0.el6.noarch.rpm

  - name: gleez.repo edited
    replace: dest=/etc/yum.repos.d/gleez.repo regexp='enabled=1' replace="enabled=0"

  - name: hhvm installed (CentOS/RHEL 7)
    package: name=hhvm enablerepo=gleez disable_gpg_check=yes

  - name: hhvm.service added
    template: src=hhvm.service.j2 dest=/usr/lib/systemd/system/hhvm.service

  - name: systemd daemon reloaded
    command: systemctl daemon-reload

  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- name: server.ini changed
  template: src=server.ini.j2 dest=/etc/hhvm/server.ini

- name: mkdir /var/run/hhvm
  file: path=/var/run/hhvm state=directory owner=vagrant group=vagrant

- name: mkdir /var/log/hhvm/
  file: path=/var/log/hhvm/ state=directory

- name: hhvm started and enabled
  service: name=hhvm state=restarted enabled=yes
