---
- block:
  - name: hop5.repo repository added (CentOS/RHEL 6)
    yum_repository:
      name: hop5
      description: www.hop5.in Centos Repository
      baseurl: http://www.hop5.in/yum/el6/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-HOP5
      enabled: no
      gpgcheck: no

  - name: hhvm installed (CentOS/RHEL 6)
    package: name=hhvm enablerepo=hop5

  - name: init.d added
    template: src=init.d.hhvm.j2 dest=/etc/init.d/hhvm

  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6

- block:
  - name: hhvm-repo repository installed (CentOS/RHEL 7)
    yum: name=http://mirrors.linuxeye.com/hhvm-repo/7/x86_64/hhvm-3.15.3-1.el7.centos.x86_64.rpm

  - name: hhvm installed (CentOS/RHEL 7)
    package: name=hhvm

  - name: hhvm.service added
    template: src=hhvm.service.centos7.j2 dest=/usr/lib/systemd/system/hhvm.service

  - name: systemd daemon reloaded
    command: systemctl daemon-reload

  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- name: server.ini changed
  template: src=server.ini.j2 dest=/etc/hhvm/server.ini

- name: mkdir /var/log/hhvm/
  file: path=/var/log/hhvm/ state=directory

- name: hhvm started and enabled
  service: name=hhvm state=restarted enabled=yes
