---
- name: develop tools installed
  package: name={{ item }} state=latest
  with_items:
    # - php-pecl-xdebug
    - subversion
    - gettext

- name: gem libraries installed
  command: sudo -u vagrant -i -- gem install {{ item }}
  # gem: name={{ item }} state=latest
  with_items:
    - sass

- name: node.js package globally installed
  command: sudo -u vagrant -i -- npm install -g {{ item }}
  # npm: name={{ item }} global=yes
  with_items:
    - grunt-cli
    - grunt-init
    - gulp-cli
    - npm-check-updates
    - bower
    - stylestats
    - plato

- include: wp-i18n.yml
- include: phpunit.yml
- include: wp-phpcs.yml
- include: opcache.yml
- include: wrk.yml
- include: selenium.yml
- include: phpmd.yml
- include: webgrind.yml

