---
- name: PHP_CodeSniffer installed
  command: sudo -u vagrant -i -- {{ home_dir }}/.phpenv/shims/composer global require 'squizlabs/php_codesniffer=2.9.*'

- name: git checkout WordPress-Coding-Standards
  git:
    repo: "{{ WordPress_Coding_Standards_repository }}"
    dest: "{{ share_path }}/wp-phpcs"
    force: yes

- name: phpcs config-set wp-phpcs
  command: sudo -u vagrant -i -- {{ home_dir }}/.phpenv/shims/phpcs --config-set installed_paths {{ share_path }}/wp-phpcs

# - name: ruleset.xml fixed
#   replace:
#     dest: "{{ share_path }}/wp-phpcs/WordPress-Core/ruleset.xml"
#     regexp: "<property name=\"indent\" value=\"4\"/>"
#     replace: "<property name=\"indent\" value=\"1\"/>"
