---
- name: git checkout wrk
  git: repo=https://github.com/wg/wrk.git dest=/home/vagrant/wrk force=yes
  become: yes
- name: make wrk
  command: make chdir=/home/vagrant/wrk
  become: yes
- name: make wrk
  copy: src=/home/vagrant/wrk/wrk dest=/usr/local/bin mode=755
  become: yes
- name: delete wrk dir
  file: path=/home/vagrant/wrk state=absent
