---
- name: yarn.repo repository added (CentOS/RHEL)
  yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
    enabled: yes
    gpgcheck: yes

- name: yarn installed
  package:
    name: yarn
    state: latest
