---
- name: percona repository installed
  yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
- name: percona-release.repo edited
  replace: dest=/etc/yum.repos.d/percona-release.repo regexp="\$releasever" replace="6"

- name: percona 5.6 installed
  yum: name={{ item }} state=latest
  with_items:
    - Percona-Server-client-56
    - Percona-Server-devel-56
    - Percona-Server-server-56
    - Percona-Server-shared-56
    # - Percona-XtraDB-Cluster-devel
    - MySQL-python
- name: my.cnf changed
  template: src=my.cnf.j2 dest=/etc/my.cnf
- name: mysql started and enabled
  service: name=mysql state=restarted enabled=yes

- name: set percona root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "localhost"
    state: present
  ignore_errors: yes

- name: set percona root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "{{ item }}"
    state: present
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: Delete blank Percona users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - localhost

- name: Drop Percona test database
  mysql_db:
     name: test
     state: absent
     login_user: "root"
     login_password: "{{ db_root_password }}"

- file: src=/var/lib/mysql/mysql.sock dest=/tmp/mysql.sock state=link
