---
- name: libselinux-python installed
  package:
    name: libselinux-python
    state: latest

- name: disable selinux
  selinux:
    state: disabled

- name: is_getenforce
  command: /usr/sbin/getenforce
  register: is_getenforce

- name: SELinux is turned off
  fail:
    msg: "SELinux is turned off. please run again, 'vagrant reload --provision'"
  when: is_getenforce.stdout == 'Enforcing'

- name: ntp installed
  package:
    name: ntp

- name: ntp started and enabled
  service:
    name: ntpd
    state: restarted
    enabled: yes

- block:
  - name: create swap space
    command: dd if=/dev/zero of=/swapfile bs=1M count=1024
    ignore_errors: yes
  - name: Make swap
    command: mkswap /swapfile
    ignore_errors: yes
  when: ansible_swaptotal_mb < 1

- name: swapon
  command: swapon /swapfile
  ignore_errors: yes

- name: edit PATH on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"

- name: edit PATH on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"

- name: include task (CentOS/RHEL 6)
  include: centos6.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 6

- name: include task (CentOS/RHEL 7)
  include: centos7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7

- include: ssh-config.yml
- include: reset.yml
