---
- name: libselinux-python installed
  yum: name=libselinux-python state=latest

- name: disable selinux
  selinux: state=disabled

- command: /usr/sbin/getenforce
  register: getenforce
- fail: msg="SELinux is turned off. please run again, 'vagrant reload --provision'"
  when: getenforce.stdout == 'Enforcing' or getenforce.stdout == 'Permissive'


- name: iptables stoped and disabled
  service: name=iptables state=stopped enabled=no

- name: ntp installed
  yum: name=ntp
- name: ntp started and enabled
  service: name=ntpd state=restarted enabled=yes

- name: create swap space
  command: dd if=/dev/zero of=/swapfile bs=1M count=1024
  ignore_errors: yes
  when: ansible_swaptotal_mb < 1
- name: Make swap
  command: mkswap /swapfile
  ignore_errors: yes
  when: ansible_swaptotal_mb < 1
- name: swapon
  command: swapon /swapfile
  ignore_errors: yes

- name: IUS repository installed
  yum: name=http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-11.ius.centos6.noarch.rpm

- name: edit PATH on .bash_profile
  lineinfile: dest={{ bash_profile }} line="export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"

- name: edit PATH on .bashrc
  lineinfile: dest={{ bashrc }} line="export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"

- include: reset.yml
