---
- name: openssl installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openssl
    - openssl-devel
    - mod_ssl

- name: stat ssl_path
  stat:
    path: /etc/pki/tls/vaw
  register: is_ssl_path

- name: mkdir ssl
  file:
    path: /etc/pki/tls/vaw
    state: directory
    owner: root
  when: not is_ssl_path.stat.exists

- name: generate a key
  command: openssl genrsa -out /etc/pki/tls/vaw/server.key 2048

- name: Generate a certificate
  command: openssl req -new -x509 -key /etc/pki/tls/vaw/server.key -out /etc/pki/tls/vaw/server.crt -days 3650 -subj /CN={{ HOSTNAME }}

- name: stat ssl.conf
  stat:
    path: /etc/httpd/conf.d/ssl.conf
  register: is_ssl_conf

- name: delete ssl.conf
  file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  when: is_ssl_conf.stat.exists
