---
- name: git checkout phpenv
  git: repo=https://github.com/CHH/phpenv.git dest=/home/vagrant/phpenv force=yes
  sudo: yes

- stat: path={{ phpenv_dir }}
  register: phpenv_path

- name: phpenv installed
  command: /home/vagrant/phpenv/bin/phpenv-install.sh
  sudo_user: vagrant
  when: not phpenv_path.stat.exists

- name: delete /home/vagrant/phpenv
  file: path=/home/vagrant/phpenv state=absent

- name: change owner and group
  file: dest={{ phpenv_dir }} state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  sudo: yes

- name: edit PATH phpenv init on .bash_profile
  lineinfile: dest={{ bash_profile }} line="export PATH=$HOME/.phpenv/bin:$PATH"

- name: edit phpenv init on .bash_profile
  lineinfile: dest={{ bash_profile }} line="eval \"$(phpenv init -)\""

- name: git checkout php-build
  git: repo=https://github.com/CHH/php-build.git dest={{ phpenv_dir }}/plugins/php-build force=yes
  sudo: yes

- name: git checkout phpenv-apache-version
  git: repo=https://github.com/thingsym/phpenv-apache-version.git dest={{ phpenv_dir }}/plugins/phpenv-apache-version force=yes
  sudo: yes
  when: server == 'apache'

- name: php.conf changed
  template: src=php.conf.j2 dest=/etc/httpd/conf.d/php.conf
  when: server == 'apache'

- name: change owner and group
  file: dest={{ phpenv_dir }} state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  sudo: yes

- name: build environment
  yum: name={{ item }} state=latest
  with_items:
      - patch
      - libxml2-devel
      - bison
      - bison-devel
      - re2c
      - openssl-devel
      - curl
      - curl-devel
      - libjpeg-devel
      - libpng-devel
      - libmcrypt-devel
      - readline-devel
      - libtidy-devel
      - libxslt-devel

- name: set default_configure_options
  template: src=default_configure_options.j2 dest={{ phpenv_dir }}/plugins/php-build/share/php-build/default_configure_options

# - stat: path=/usr/lib64/httpd/modules
#   register: modules_path

# - file: path=/usr/lib64/httpd/modules owner=vagrant group=vagrant
#   when: modules_path.stat.exists

- stat: path=/usr/lib64/httpd/modules/libphp5.so
  register: libphp5_path

- file: path=/usr/lib64/httpd/modules/libphp5.so owner=vagrant group=vagrant
  when: libphp5_path.stat.exists

- stat: path=/usr/lib64/httpd/modules/libphp7.so
  register: libphp7_path

- file: path=/usr/lib64/httpd/modules/libphp7.so owner=vagrant group=vagrant
  when: libphp7_path.stat.exists

- name: mkdir /var/run/php-fpm
  file: path=/var/run/php-fpm state=directory owner=nginx group=nginx
  when: server == "nginx" and fastcgi == "php-fpm"

- name: mkdir /var/log/php-fpm
  file: path=/var/log/php-fpm state=directory owner=nobody group=nobody
  when: server == "nginx" and fastcgi == "php-fpm"

- stat: path={{ phpenv_dir }}/versions/{{ php_version | default(5.6.12) }}
  register: php_path

- name: php installed by phpenv.sh
  command: sudo -u vagrant -i -- /vagrant/command/phpenv.sh {{ php_version | default(5.6.12) }}
  when: not php_path.stat.exists

- name: php.ini changed
  template: src=php.ini.j2 dest={{ phpenv_dir }}/versions/{{ php_version | default(5.6.12) }}/etc/php.ini

- name: touch php.log
  file: path=/var/log/php.log state=touch mode=0666

- name: phpenv global by phpenv.sh
  command: sudo -u vagrant -i -- /vagrant/command/phpenv.sh {{ php_version | default(5.6.12) }}
  when: not php_path.stat.exists

- name: php-fpm added to /usr/sbin/
  command: cp {{ phpenv_dir }}/versions/{{ php_version | default(5.6.12) }}/sbin/php-fpm /usr/sbin/php-fpm
  when: server == "nginx" and fastcgi == "php-fpm"

- name: change mode php-fpm
  file: dest=/usr/sbin/php-fpm mode=0755
  when: server == "nginx" and fastcgi == "php-fpm"

- name: php-fpm.conf added
  command: cp /vagrant/roles/phpenv/templates/php-fpm.conf {{ phpenv_dir }}/versions/{{ php_version | default(5.6.12) }}/etc/php-fpm.conf
  when: server == "nginx" and fastcgi == "php-fpm"

- name: init.d.php-fpm added to /etc/init.d/
  command: cp /tmp/php-build/source/{{ php_version | default(5.6.12) }}/sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm
  when: server == "nginx" and fastcgi == "php-fpm"

- name: change mode php-fpm
  file: dest=/etc/init.d/php-fpm mode=0755
  when: server == "nginx" and fastcgi == "php-fpm"

- name: chkconfig php-fpm added
  command: chkconfig --add php-fpm
  when: server == "nginx" and fastcgi == "php-fpm"

- name: php-fpm start and enabled
  service: name=php-fpm state=restarted enabled=yes
  when: server == "nginx" and fastcgi == "php-fpm"

- file: src={{ phpenv_dir }}/shims/php dest=/usr/bin/php state=link force=yes
