---
- name: mkdir /var/run/php-fpm
  file:
    path: /var/run/php-fpm
    state: directory
    owner: vagrant
    group: vagrant

- name: mkdir /var/log/php-fpm
  file:
    path: /var/log/php-fpm
    state: directory
    owner: vagrant
    group: vagrant

- block:
  - name: stat init_php_fpm
    stat:
      path: /etc/init.d/php-fpm
    register: is_init_php_fpm

  - name: chkconfig php-fpm added (CentOS/RHEL 6)
    command: chkconfig --add php-fpm
    when: is_init_php_fpm.stat.exists
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 6

- name: php-fpm start and enabled
  service:
    name: php-fpm
    state: restarted
    enabled: yes
